### ISSUE TITLE
`find_optimal_celestial_wcs` does not accept ImageHDU, PrimaryHDU and `CompImageHDU`

### ISSUE THREAD

**Issue by cylammarco** [astropy/reproject#323]
@pha12kt found that `find_optimal_celestial_wcs` does not accept ImageHDU, PrimaryHDU. In the below examples, `img` is an ImageHDU object.

Failing to accept an ImageHDU object:
```
>>> find_optimal_celestial_wcs(img)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/reproject/mosaicking/wcs_helpers.py", line 72, in find_optimal_celestial_wcs
    input_shapes = [parse_input_shape(shape) for shape in input_data]
TypeError: 'ImageHDU' object is not iterable
```

Failing to accept a PrimaryHDU object
```
>>> find_optimal_celestial_wcs(fits.PrimaryHDU(img.data, img.header))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/reproject/mosaicking/wcs_helpers.py", line 72, in find_optimal_celestial_wcs
    input_shapes = [parse_input_shape(shape) for shape in input_data]
TypeError: 'PrimaryHDU' object is not iterable
```

But it accepts a list of ImageHDU, or an HDUList
```
>>> find_optimal_celestial_wcs([img])
(WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 234.05721112817054  39.73269564616722  
CRPIX : 2653.490914560424  2562.2117672994214  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : -1.1005555796953587e-05  1.1005555796953587e-05  
NAXIS : 0  0, (5123, 5307))

>>> find_optimal_celestial_wcs(fits.HDUList(img))
(WCS Keywords

Number of WCS axes: 2
CTYPE : 'RA---TAN'  'DEC--TAN'  
CRVAL : 234.05721112817054  39.73269564616722  
CRPIX : 2653.490914560424  2562.2117672994214  
PC1_1 PC1_2  : 1.0  0.0  
PC2_1 PC2_2  : 0.0  1.0  
CDELT : -1.1005555796953587e-05  1.1005555796953587e-05  
NAXIS : 0  0, (5123, 5307))

```

**Comment by cylammarco** [comment]
Suggested Fix: Perform a type check for `ImageHDU`, `PrimaryHDU`, and `CompImageHDU`, and then turn them into a list so that the next line

https://github.com/astropy/reproject/blob/0af9e04608f4772db068c70549dfb65e907dc41f/reproject/mosaicking/wcs_helpers.py#L77

can continue the work.
